services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://backend:8000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: